import { School } from "../types";

export const SCHOOLS: School[] = [
  {
    id: "seoul-science",
    name: "서울과학고등학교",
    type: "과학고",
    location: "서울특별시 종로구 혜화동",
    studentCount: "약 360명",
    history: "1983년 개교 (국내 최초 과학고)",
    description: "대한민국 과학영재교육의 발상지로, 최고의 연구 중심 교육 과정을 운영합니다.",
    subjectWeights: { korean: 1, math: 2.5, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 88,
    difficulty: 2,
  },
  {
    id: "gyeonggi-science",
    name: "경기과학고등학교",
    type: "과학고",
    location: "경기도 수원시 장안구",
    studentCount: "약 370명",
    history: "1983년 개교",
    description: "연구 중심의 교육과 자유로운 학문적 분위기로 유명한 세계적 영재학교입니다.",
    subjectWeights: { korean: 1, math: 2, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 86,
    difficulty: 1.5,
  },
  {
    id: "daejeon-science",
    name: "대전과학고등학교",
    type: "과학고",
    location: "대전광역시 유성구",
    studentCount: "약 270명",
    history: "1984년 개교",
    description: "대덕연구단지와의 인프라를 활용한 전문 과학 교육이 강점인 학교입니다.",
    subjectWeights: { korean: 1, math: 2, english: 1, science: 2, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 83,
    difficulty: 1,
  },
  {
    id: "daegu-science",
    name: "대구과학고등학교",
    type: "과학고",
    location: "대구광역시 수성구",
    studentCount: "약 280명",
    history: "1988년 개교",
    description: "거대한 과학 인재 네트워크를 보유한 영남권 최고의 과학 교육 기관입니다.",
    subjectWeights: { korean: 1, math: 2, english: 1, science: 2, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 82,
    difficulty: 1,
  },
  {
    id: "gwangju-science",
    name: "광주과학고등학교",
    type: "과학고",
    location: "광주광역시 북구",
    studentCount: "약 290명",
    history: "1984년 개교",
    description: "인공지능 및 첨단 기술 중심의 융합 인재 양성을 목표로 합니다.",
    subjectWeights: { korean: 1, math: 2, english: 1, science: 2.2, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 81,
    difficulty: 1,
  },
  {
    id: "busan-science",
    name: "부산과학고등학교",
    type: "과학고",
    location: "부산광역시 금정구",
    studentCount: "약 300명",
    history: "2003년 개교 (장영실고 전신)",
    description: "해양 및 기초과학 연구에 특화된 실천 중심의 과학고등학교입니다.",
    subjectWeights: { korean: 1, math: 2.3, english: 1, science: 2.3, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 80,
    difficulty: 0.5,
  },
  {
    id: "incheon-haneul",
    name: "인천하늘고등학교",
    type: "과학고",
    location: "인천광역시 남동구",
    studentCount: "약 300명",
    history: "2004년 개교",
    description: "창의적 과학 인재 양성을 목표로 하는 인천권 대표 과학고등학교입니다.",
    subjectWeights: { korean: 1, math: 2.3, english: 1, science: 2.5, social: 0.7 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 80,
    difficulty: 0.5,
  },
  {
    id: "sejong-science",
    name: "세종과학고등학교",
    type: "과학고",
    location: "서울특별시 구로구",
    studentCount: "약 360명",
    history: "1989년 개교",
    description: "서울 서남권 대표 과학고로, 수학·과학 심화 연구 활동이 활발한 학교입니다.",
    subjectWeights: { korean: 1, math: 2.2, english: 1, science: 2.3, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 79,
    difficulty: 0.5,
  },
  {
    id: "hansung-science",
    name: "한성과학고등학교",
    type: "과학고",
    location: "서울특별시 성북구",
    studentCount: "약 330명",
    history: "1992년 개교",
    description: "기초과학 중심 교육과 연구 활동을 강조하는 서울권 명문 과학고입니다.",
    subjectWeights: { korean: 1, math: 2.1, english: 1, science: 2.2, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 79,
    difficulty: 0.5,
  },
  {
    id: "seoul-foreign",
    name: "서울외국어고등학교",
    type: "외고",
    location: "서울특별시 노원구",
    studentCount: "약 700명",
    history: "1994년 설립",
    description: "글로벌 인문 소양과 외국어 구사 능력을 겸비한 인재를 배출합니다.",
    subjectWeights: { korean: 1.5, math: 1, english: 2.5, science: 0.5, social: 1 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 82,
    difficulty: 0.5,
  },
  {
    id: "busan-foreign",
    name: "부산외국어고등학교",
    type: "외고",
    location: "부산광역시 연제구",
    studentCount: "약 720명",
    history: "1985년 설립",
    description: "글로벌 비즈니스와 국제 감각을 갖춘 인재 양성에 특화되어 있습니다.",
    subjectWeights: { korean: 1.5, math: 1, english: 2.2, science: 0.5, social: 1.2 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 79,
    difficulty: 0,
  },
  {
    id: "daewon-foreign",
    name: "대원외국어고등학교",
    type: "외고",
    location: "서울특별시 광진구",
    studentCount: "약 750명",
    history: "1984년 설립",
    description: "명실상부 국내 최고의 진학 실적과 언어 교육 체계를 자랑합니다.",
    subjectWeights: { korean: 1.4, math: 1, english: 2.6, science: 0.5, social: 1 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 84,
    difficulty: 1,
  },
  {
    id: "hanyoung-foreign",
    name: "한영외국어고등학교",
    type: "외고",
    location: "서울특별시 강동구",
    studentCount: "약 730명",
    history: "1990년 개교",
    description: "심화된 전공 언어 수업과 국제적 안목을 키워주는 커리큘럼이 특징입니다.",
    subjectWeights: { korean: 1.4, math: 1, english: 2.4, science: 0.5, social: 1 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 81,
    difficulty: 0.5,
  },
  {
    id: "goyang-foreign",
    name: "고양외국어고등학교",
    type: "외고",
    location: "경기도 고양시 덕양구",
    studentCount: "약 780명",
    history: "2002년 개교",
    description: "창의적 인문학적 사고를 바탕으로 미래 사회의 리더를 양성합니다.",
    subjectWeights: { korean: 1.4, math: 1, english: 2.3, science: 0.5, social: 1 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 79,
    difficulty: 0,
  },
  {
    id: "sungnam-foreign",
    name: "성남외국어고등학교",
    type: "외고",
    location: "경기도 성남시 수정구",
    studentCount: "약 600명",
    history: "2006년 개교",
    description: "최신 시설과 맞춤형 입시 지도로 명성이 높은 명문 공립 외고입니다.",
    subjectWeights: { korean: 1.5, math: 1, english: 2.2, science: 0.5, social: 1 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 78,
    difficulty: 0,
  },
  {
    id: "suwon-fl",
    name: "수원외국어고등학교",
    type: "외고",
    location: "경기도 수원시",
    studentCount: "약 650명",
    history: "2001년 개교",
    description: "경기권 대표 외고.",
    subjectWeights: { korean: 1.5, math: 1, english: 2.3, science: 0.6, social: 1 },
    gradeWeights: { semesterWeights: [0.1, 0.15, 0.2, 0.2, 0.2, 0.15] },
    cutline: 78,
    difficulty: 0,
  },
  {
    id: "incheon-semiconductor",
    name: "인천공업고등학교(반도체 특화)",
    type: "과학고",
    location: "인천광역시 연수구",
    studentCount: "약 320명",
    history: "2010년 개교",
    description: "반도체 및 전자공학 실무 중심의 특화 교육과정을 운영합니다.",
    subjectWeights: { korean: 1, math: 2, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 77,
    difficulty: 0,
  },
  {
    id: "chungbuk-semiconductor",
    name: "충북반도체고등학교",
    type: "과학고",
    location: "충청북도 청주시 흥덕구",
    studentCount: "약 300명",
    history: "2012년 개교",
    description: "반도체 산업 맞춤형 교육과 실습 중심의 특화 학교입니다.",
    subjectWeights: { korean: 1, math: 2.2, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 76,
    difficulty: 0,
  },
  {
    id: "gyeonggi-semiconductor",
    name: "경기반도체고등학교",
    type: "과학고",
    location: "경기도 수원시 권선구",
    studentCount: "약 320명",
    history: "2011년 개교",
    description: "최신 반도체 장비와 연계한 실습 교육을 강조합니다.",
    subjectWeights: { korean: 1, math: 2.3, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 77,
    difficulty: 0,
  },
  {
    id: "daejeon-semiconductor",
    name: "대전반도체고등학교",
    type: "과학고",
    location: "대전광역시 유성구",
    studentCount: "약 310명",
    history: "2013년 개교",
    description: "반도체 연구 인프라와 연계한 프로젝트 중심 교육 제공.",
    subjectWeights: { korean: 1, math: 2.2, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 76,
    difficulty: 0,
  },
  {
    id: "busan-semiconductor",
    name: "부산반도체고등학교",
    type: "과학고",
    location: "부산광역시 금정구",
    studentCount: "약 330명",
    history: "2010년 개교",
    description: "해양 및 반도체 융합 교육을 제공하는 특화 공업고입니다.",
    subjectWeights: { korean: 1, math: 2.3, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [0.05, 0.1, 0.15, 0.2, 0.25, 0.25] },
    cutline: 76,
    difficulty: 0,
  },
];