import { School } from "../types";

export const SCHOOLS: School[] = [
  {
    id: "seoul-science",
    name: "서울과학고등학교",
    type: "과학고",
    location: "서울",
    studentCount: "120명",
    history: "1989년 개교",
    description: "전국 최고 수준의 과학영재학교로, 이공계 인재 양성에 특화된 교육과정을 운영합니다.",
    subjectWeights: { korean: 1, math: 3, english: 1, science: 3, social: 0.5 },
    gradeWeights: { semesterWeights: [1, 1, 2, 2] },
    cutline: 88,
    difficulty: 2,
  },
  {
    id: "gyeonggi-science",
    name: "경기과학고등학교",
    type: "과학고",
    location: "경기",
    studentCount: "120명",
    history: "1991년 개교",
    description: "수학·과학 특기자를 위한 영재학교로, 자기주도 연구 중심 교육을 지향합니다.",
    subjectWeights: { korean: 1, math: 3, english: 1, science: 3, social: 0.5 },
    gradeWeights: { semesterWeights: [1, 1, 2, 2] },
    cutline: 86,
    difficulty: 1.5,
  },
  {
    id: "daejeon-science",
    name: "대전과학고등학교",
    type: "과학고",
    location: "대전",
    studentCount: "90명",
    history: "1992년 개교",
    description: "대덕특구와 연계한 과학 연구 환경 속에서 심화 학습을 제공합니다.",
    subjectWeights: { korean: 1, math: 2.5, english: 1, science: 2.5, social: 0.5 },
    gradeWeights: { semesterWeights: [1, 1.5, 2, 2] },
    cutline: 83,
    difficulty: 1,
  },
  {
    id: "hankuk-foreign",
    name: "한국외국어대학교부속외국어고등학교",
    type: "외고",
    location: "서울",
    studentCount: "378명",
    history: "1984년 개교",
    description: "다양한 외국어 전공 과정을 통해 글로벌 인재를 양성하는 외국어고등학교입니다.",
    subjectWeights: { korean: 2, math: 1, english: 4, science: 0.5, social: 2 },
    gradeWeights: { semesterWeights: [1, 1, 2, 2] },
    cutline: 85,
    difficulty: 1,
  },
  {
    id: "daewon-foreign",
    name: "대원외국어고등학교",
    type: "외고",
    location: "서울",
    studentCount: "342명",
    history: "1988년 개교",
    description: "어문계열 심화 교육과 다양한 국제 교류 프로그램으로 외교·통상 분야 인재를 배출합니다.",
    subjectWeights: { korean: 2, math: 1, english: 3.5, science: 0.5, social: 2.5 },
    gradeWeights: { semesterWeights: [1, 1, 2, 2] },
    cutline: 82,
    difficulty: 0.5,
  },
  {
    id: "busan-foreign",
    name: "부산외국어고등학교",
    type: "외고",
    location: "부산",
    studentCount: "258명",
    history: "1993년 개교",
    description: "부산·경남 권역의 대표 외고로 영어·일본어·중국어 등 전문 언어 교육을 제공합니다.",
    subjectWeights: { korean: 2, math: 1, english: 3, science: 0.5, social: 2 },
    gradeWeights: { semesterWeights: [1, 1.5, 2, 2] },
    cutline: 78,
    difficulty: 0,
  },
];